# Generated by Django 5.0.7 on 2024-07-30 11:41

import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportRequestBase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created at"),
                ),
                (
                    "modified_at",
                    models.DateTimeField(auto_now=True, verbose_name="Modified at"),
                ),
                (
                    "subject",
                    models.CharField(
                        db_comment="The subject of the contact message.",
                        help_text="The main topic of your message.",
                        max_length=100,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        db_comment="The full name of the person contacting.",
                        help_text="Your complete name as you'd like us to address you.",
                        max_length=150,
                        verbose_name="Full Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_comment="The email address of the person contacting.",
                        help_text="Your email address where we can send a reply.",
                        max_length=254,
                        verbose_name="Email",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        db_comment="The contact message content.",
                        help_text="The detailed message or inquiry you wish to submit.",
                        verbose_name="Message",
                    ),
                ),
            ],
            options={
                "verbose_name": "Basic Contact",
                "verbose_name_plural": "Basic Contacts",
                "db_table": "sage_contact_base",
                "db_table_comment": "Table to store basic contact information including subject, full name, email, and message.",
                "default_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="SupportRequestWithPhone",
            fields=[
                (
                    "supportrequestbase_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sage_contact.supportrequestbase",
                    ),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        db_comment="The international phone number of the person contacting.",
                        help_text="Your phone number in international format, e.g., +12025550109.",
                        max_length=128,
                        region=None,
                        verbose_name="Phone Number",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact With Phone",
                "verbose_name_plural": "Contacts With Phone",
                "db_table": "sage_contact_with_phone",
                "db_table_comment": "Table to store contact information including phone number along with basic contact details.",
            },
            bases=("sage_contact.supportrequestbase",),
        ),
        migrations.CreateModel(
            name="SupportRequestWithLocation",
            fields=[
                (
                    "supportrequestwithphone_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sage_contact.supportrequestwithphone",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        db_comment="The country of the person contacting.",
                        help_text="Select the country you are contacting us from. Useful for regional marketing campaigns and statistics.",
                        max_length=2,
                        verbose_name="Country",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        db_comment="The IP address from which the contact form was submitted.",
                        help_text="For internal use only. Your IP address is recorded for security and demographic purposes.",
                        null=True,
                        unpack_ipv4=True,
                        verbose_name="IP Address",
                    ),
                ),
                (
                    "ip_country",
                    models.CharField(
                        blank=True,
                        db_comment="The country derived from the IP address.",
                        help_text="The country derived from the IP address.",
                        max_length=255,
                        null=True,
                        verbose_name="IP Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contact With Location",
                "verbose_name_plural": "Contacts With Location",
                "db_table": "sage_contact_with_location",
                "db_table_comment": "Table to store contact information including location details along with phone and basic contact details.",
            },
            bases=("sage_contact.supportrequestwithphone",),
        ),
        migrations.CreateModel(
            name="FullSupportRequest",
            fields=[
                (
                    "supportrequestwithlocation_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="sage_contact.supportrequestwithlocation",
                    ),
                ),
                (
                    "contacted_before",
                    models.BooleanField(
                        db_comment="Indicates whether the person has contacted the company before.",
                        default=False,
                        help_text="Check this box if you have made previous contact. It helps us track our ongoing relationship with you.",
                        verbose_name="Contacted Before",
                    ),
                ),
                (
                    "contact_reason",
                    models.CharField(
                        choices=[
                            ("support", "Support"),
                            ("sales", "Sales Inquiry"),
                            ("feedback", "Feedback"),
                        ],
                        db_comment="The reason for the contact, used to categorize and prioritize the contact.",
                        help_text="Specify the reason for your contact. This helps us to direct your query to the appropriate team.",
                        max_length=200,
                        verbose_name="Reason for Contact",
                    ),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("text", "Text Message"),
                        ],
                        db_comment="The contact's preferred method of communication.",
                        help_text="Indicate your preferred method of communication. We respect your choice and will contact you accordingly.",
                        max_length=50,
                        verbose_name="Preferred Contact Method",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        db_comment="A reference to the User model if the contact is made by a registered user.",
                        help_text="If you are a registered user, this field links your account to the contact form.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Full Contact",
                "verbose_name_plural": "Full Contacts",
                "db_table": "sage_full_contact",
                "db_table_comment": "Table to store complete contact information including user reference, contact history, reason for contact, preferred contact method, and all details from location, phone, and basic contact.",
            },
            bases=("sage_contact.supportrequestwithlocation",),
        ),
    ]
