# constants.py

SAGE_CONTACT_GEOIP_PATH = None

# Email
EMAIL_CONFIRMATION_SUBJECT = "We have received your contact request"
EMAIL_EXTRA_HEADERS_MIME_VERSION = "1.0"
EMAIL_EXTRA_HEADERS_CONTENT_TYPE = "text/html; charset=UTF-8"
EMAIL_EXTRA_HEADERS_CONTENT_TRANSFER_ENCODING = "quoted-printable"
EMAIL_EXTRA_HEADERS_X_PRIORITY = "3"
EMAIL_EXTRA_HEADERS_X_AUTO_RESPONSE_SUPPRESS = "All"
EMAIL_EXTRA_HEADERS_X_SPAMD_RESULT = "default: False [-0.90 / 15.00]"
